import type { NextPage } from 'next';
import Head from 'next/head';
import Login from '../components/Login';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Login With Token | Gitlab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
    </div>
  );
};

export default Home;
